# Generated by Django 4.0.3 on 2023-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0002_item_alter_map_options_alter_monster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='monsters',
            field=models.ManyToManyField(null=True, related_name='maps', to='haven.monster'),
        ),
    ]
