# Generated by Django 4.0.3 on 2023-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_alter_map_monsters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='monsters',
            field=models.ManyToManyField(blank=True, related_name='maps', to='haven.monster'),
        ),
    ]
