# Generated by Django 4.0.3 on 2023-05-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0004_alter_map_monsters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='items', verbose_name='아이템 이미지'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='monsters', verbose_name='몬스터 이미지'),
        ),
    ]
