# Generated by Django 4.0.3 on 2023-05-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0008_npc_quest_type_alter_quest_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='process_map',
        ),
        migrations.AddField(
            model_name='quest',
            name='recommended_map',
            field=models.ManyToManyField(related_name='quests', to='haven.map'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='finish_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_finish', to='haven.map'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='finish_npc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_finish', to='haven.npc'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='haven.questdetail'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_start', to='haven.map'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_npc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_start', to='haven.npc'),
        ),
    ]
