# Generated by Django 4.0.3 on 2023-08-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0009_remove_quest_process_map_quest_recommended_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='x 좌표')),
                ('y', models.IntegerField(verbose_name='y 좌표')),
                ('size', models.IntegerField(verbose_name='원 크기')),
            ],
            options={
                'verbose_name': '좌표',
                'verbose_name_plural': '좌표',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='map',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='haven.coordinate'),
        ),
    ]
